# Generated by Django 3.2.12 on 2022-02-24 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraFish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fisheye', models.TextField(default='')),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fish', to='camsapp.camera')),
            ],
        ),
    ]
