# Generated by Django 3.2.12 on 2022-02-15 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('srvapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True)),
                ('picture', models.ImageField(upload_to='camerashots')),
                ('ai_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srvapp.aiserver')),
                ('cam_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srvapp.camserver')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'камера',
                'verbose_name_plural': 'камеры',
            },
        ),
    ]
