# Generated by Django 3.2.12 on 2022-02-15 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_server_id', models.IntegerField(default=1)),
                ('ip_addr', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(default=554)),
                ('slug_after', models.CharField(default='av0_1', max_length=128)),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('picture', models.ImageField(upload_to='camerashots')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'камера',
                'verbose_name_plural': 'камеры',
            },
        ),
    ]
