# Generated by Django 3.2.12 on 2022-02-21 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srvapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseserverlink', models.URLField(blank=True)),
                ('camlink', models.URLField(blank=True)),
                ('picture', models.ImageField(upload_to='camerashots')),
                ('aiserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srvapp.aiserver')),
                ('anserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srvapp.anserver')),
                ('camserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srvapp.camserver')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'камера',
                'verbose_name_plural': 'камеры',
            },
        ),
        migrations.CreateModel(
            name='CameraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camerainfo', models.TextField(default='')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camsapp.camera')),
            ],
        ),
    ]
